server:
  port: 8080

spring:
  # 数据源配置
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver # mysql的驱动你可以配置别的关系型数据库
      url: jdbc:mysql://192.168.8.66:3306/bim_xiaoxingjijian?serverTimezone=Asia/Shanghai&characterEncoding=utf-8&useSSL=false&useUnicode=true #数据源地址
      username: xiaoxingjijian # 用户名
      password: 123456 # 密码

redis:
  host: 192.168.8.66
  port: 6379
  timeout: 3600
  password:
  database: 0
  pool:
    maxTotal: 1000
    maxIdle: 100
    maxWaitMillis: 100000
    minIdle: 80



